---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%",
  dpi = 300
)
```

# HMSr

<!-- badges: start -->
<!-- badges: end -->

**NOTE: MOST OF THE FUNCTION HAVE NO PRACTICAL USE OUTSIDE [HMS](https://www.hms.is/)**

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("karsfri/HMSr")
```
## Example

The default template in ggplot2 is readable, but ugly:

```{r example}
library(tidyverse)
library(lubridate)
library(HMSr)


data("economics")

  economics %>%
    filter(date == lubridate::floor_date(date, "year"), year(date) > 2000) %>%
    gather(var, val, -date) %>%
    ggplot(aes(date, val, color = var)) +
    geom_col(width = 0.3) +
    geom_point() +
    labs(
      title = "Lollipops and stuff",
      subtitle = "With HMS colors",
      x = NULL,
      y = NULL,
      caption = "Source: None of your business :P"
    ) +
    facet_wrap(~var, scales = "free_y")


```

The *theme_set_hms()* function sets *theme_hms* as the default theme, along with default colors for some of the more popular geoms.

Notice also the helper function, *label_isl()*.

```{r cars}
theme_set_hms()

  economics %>%
    filter(date == lubridate::floor_date(date, "year"), year(date) > 2000) %>%
    gather(var, val, -date) %>%
    ggplot(aes(date, val, color = var)) +
    geom_col(width = 0.3) +
    geom_point() +
    theme_hms() +
    scale_color_manual(values = palette_dark) +
    scale_y_continuous(labels = label_isl()) +
    labs(
      title = "Lollipops and stuff",
      subtitle = "With HMS colors",
      x = NULL,
      y = NULL,
      caption = "Source: None of your business :P"
    ) +
    facet_wrap(~var, scales = "free_y")
```


